//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOnlineShopConsumer.BankReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Bank_ApplicationWCFREST")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long accountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime createAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long identityCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int phoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime updateAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long accountId {
            get {
                return this.accountIdField;
            }
            set {
                if ((this.accountIdField.Equals(value) != true)) {
                    this.accountIdField = value;
                    this.RaisePropertyChanged("accountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime createAt {
            get {
                return this.createAtField;
            }
            set {
                if ((this.createAtField.Equals(value) != true)) {
                    this.createAtField = value;
                    this.RaisePropertyChanged("createAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dob {
            get {
                return this.dobField;
            }
            set {
                if ((this.dobField.Equals(value) != true)) {
                    this.dobField = value;
                    this.RaisePropertyChanged("dob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fullNameField, value) != true)) {
                    this.fullNameField = value;
                    this.RaisePropertyChanged("fullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gender {
            get {
                return this.genderField;
            }
            set {
                if ((this.genderField.Equals(value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long identityCard {
            get {
                return this.identityCardField;
            }
            set {
                if ((this.identityCardField.Equals(value) != true)) {
                    this.identityCardField = value;
                    this.RaisePropertyChanged("identityCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((this.phoneNumberField.Equals(value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime updateAt {
            get {
                return this.updateAtField;
            }
            set {
                if ((this.updateAtField.Equals(value) != true)) {
                    this.updateAtField = value;
                    this.RaisePropertyChanged("updateAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/Bank_ApplicationWCFREST")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long accountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal balanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime createAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string saltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime updateAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                if ((this.accountNumberField.Equals(value) != true)) {
                    this.accountNumberField = value;
                    this.RaisePropertyChanged("accountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal balance {
            get {
                return this.balanceField;
            }
            set {
                if ((this.balanceField.Equals(value) != true)) {
                    this.balanceField = value;
                    this.RaisePropertyChanged("balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime createAt {
            get {
                return this.createAtField;
            }
            set {
                if ((this.createAtField.Equals(value) != true)) {
                    this.createAtField = value;
                    this.RaisePropertyChanged("createAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pin {
            get {
                return this.pinField;
            }
            set {
                if ((object.ReferenceEquals(this.pinField, value) != true)) {
                    this.pinField = value;
                    this.RaisePropertyChanged("pin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string salt {
            get {
                return this.saltField;
            }
            set {
                if ((object.ReferenceEquals(this.saltField, value) != true)) {
                    this.saltField = value;
                    this.RaisePropertyChanged("salt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime updateAt {
            get {
                return this.updateAtField;
            }
            set {
                if ((this.updateAtField.Equals(value) != true)) {
                    this.updateAtField = value;
                    this.RaisePropertyChanged("updateAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartnerAccount", Namespace="http://schemas.datacontract.org/2004/07/Bank_ApplicationWCFREST")]
    [System.SerializableAttribute()]
    public partial class PartnerAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long accountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime createAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long partnerAccount1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string saltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime updateAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                if ((this.accountNumberField.Equals(value) != true)) {
                    this.accountNumberField = value;
                    this.RaisePropertyChanged("accountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime createAt {
            get {
                return this.createAtField;
            }
            set {
                if ((this.createAtField.Equals(value) != true)) {
                    this.createAtField = value;
                    this.RaisePropertyChanged("createAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long partnerAccount1 {
            get {
                return this.partnerAccount1Field;
            }
            set {
                if ((this.partnerAccount1Field.Equals(value) != true)) {
                    this.partnerAccount1Field = value;
                    this.RaisePropertyChanged("partnerAccount1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string salt {
            get {
                return this.saltField;
            }
            set {
                if ((object.ReferenceEquals(this.saltField, value) != true)) {
                    this.saltField = value;
                    this.RaisePropertyChanged("salt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime updateAt {
            get {
                return this.updateAtField;
            }
            set {
                if ((this.updateAtField.Equals(value) != true)) {
                    this.updateAtField = value;
                    this.RaisePropertyChanged("updateAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://schemas.datacontract.org/2004/07/Bank_ApplicationWCFREST")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string billIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime createAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal feeTransactionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long receiverAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long senderAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime updateAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                if ((this.amountField.Equals(value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string billId {
            get {
                return this.billIdField;
            }
            set {
                if ((object.ReferenceEquals(this.billIdField, value) != true)) {
                    this.billIdField = value;
                    this.RaisePropertyChanged("billId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string content {
            get {
                return this.contentField;
            }
            set {
                if ((object.ReferenceEquals(this.contentField, value) != true)) {
                    this.contentField = value;
                    this.RaisePropertyChanged("content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime createAt {
            get {
                return this.createAtField;
            }
            set {
                if ((this.createAtField.Equals(value) != true)) {
                    this.createAtField = value;
                    this.RaisePropertyChanged("createAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal feeTransaction {
            get {
                return this.feeTransactionField;
            }
            set {
                if ((this.feeTransactionField.Equals(value) != true)) {
                    this.feeTransactionField = value;
                    this.RaisePropertyChanged("feeTransaction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long receiverAccountNumber {
            get {
                return this.receiverAccountNumberField;
            }
            set {
                if ((this.receiverAccountNumberField.Equals(value) != true)) {
                    this.receiverAccountNumberField = value;
                    this.RaisePropertyChanged("receiverAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long senderAccountNumber {
            get {
                return this.senderAccountNumberField;
            }
            set {
                if ((this.senderAccountNumberField.Equals(value) != true)) {
                    this.senderAccountNumberField = value;
                    this.RaisePropertyChanged("senderAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime updateAt {
            get {
                return this.updateAtField;
            }
            set {
                if ((this.updateAtField.Equals(value) != true)) {
                    this.updateAtField = value;
                    this.RaisePropertyChanged("updateAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryTransaction", Namespace="http://schemas.datacontract.org/2004/07/Bank_ApplicationWCFREST")]
    [System.SerializableAttribute()]
    public partial class HistoryTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long accountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime createAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal feeTransactionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long transactionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                if ((this.accountNumberField.Equals(value) != true)) {
                    this.accountNumberField = value;
                    this.RaisePropertyChanged("accountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                if ((this.amountField.Equals(value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime createAt {
            get {
                return this.createAtField;
            }
            set {
                if ((this.createAtField.Equals(value) != true)) {
                    this.createAtField = value;
                    this.RaisePropertyChanged("createAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal feeTransaction {
            get {
                return this.feeTransactionField;
            }
            set {
                if ((this.feeTransactionField.Equals(value) != true)) {
                    this.feeTransactionField = value;
                    this.RaisePropertyChanged("feeTransaction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                if ((this.transactionIdField.Equals(value) != true)) {
                    this.transactionIdField = value;
                    this.RaisePropertyChanged("transactionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankReference.IBank")]
    public interface IBank {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/AddCustomer", ReplyAction="http://tempuri.org/IBank/AddCustomerResponse")]
        bool AddCustomer(BankOnlineShopConsumer.BankReference.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/AddCustomer", ReplyAction="http://tempuri.org/IBank/AddCustomerResponse")]
        System.Threading.Tasks.Task<bool> AddCustomerAsync(BankOnlineShopConsumer.BankReference.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/AddAccount", ReplyAction="http://tempuri.org/IBank/AddAccountResponse")]
        bool AddAccount(BankOnlineShopConsumer.BankReference.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/AddAccount", ReplyAction="http://tempuri.org/IBank/AddAccountResponse")]
        System.Threading.Tasks.Task<bool> AddAccountAsync(BankOnlineShopConsumer.BankReference.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/LoginAccount", ReplyAction="http://tempuri.org/IBank/LoginAccountResponse")]
        bool LoginAccount(BankOnlineShopConsumer.BankReference.Account customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/LoginAccount", ReplyAction="http://tempuri.org/IBank/LoginAccountResponse")]
        System.Threading.Tasks.Task<bool> LoginAccountAsync(BankOnlineShopConsumer.BankReference.Account customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/AddPartnerAccount", ReplyAction="http://tempuri.org/IBank/AddPartnerAccountResponse")]
        bool AddPartnerAccount(BankOnlineShopConsumer.BankReference.PartnerAccount account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/AddPartnerAccount", ReplyAction="http://tempuri.org/IBank/AddPartnerAccountResponse")]
        System.Threading.Tasks.Task<bool> AddPartnerAccountAsync(BankOnlineShopConsumer.BankReference.PartnerAccount account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/LoginPartnerAccount", ReplyAction="http://tempuri.org/IBank/LoginPartnerAccountResponse")]
        bool LoginPartnerAccount(BankOnlineShopConsumer.BankReference.PartnerAccount partner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/LoginPartnerAccount", ReplyAction="http://tempuri.org/IBank/LoginPartnerAccountResponse")]
        System.Threading.Tasks.Task<bool> LoginPartnerAccountAsync(BankOnlineShopConsumer.BankReference.PartnerAccount partner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/AddTransaction", ReplyAction="http://tempuri.org/IBank/AddTransactionResponse")]
        int AddTransaction(BankOnlineShopConsumer.BankReference.Transaction transaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/AddTransaction", ReplyAction="http://tempuri.org/IBank/AddTransactionResponse")]
        System.Threading.Tasks.Task<int> AddTransactionAsync(BankOnlineShopConsumer.BankReference.Transaction transaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/AddHistoryTransaction", ReplyAction="http://tempuri.org/IBank/AddHistoryTransactionResponse")]
        bool AddHistoryTransaction(BankOnlineShopConsumer.BankReference.HistoryTransaction historyTransaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/AddHistoryTransaction", ReplyAction="http://tempuri.org/IBank/AddHistoryTransactionResponse")]
        System.Threading.Tasks.Task<bool> AddHistoryTransactionAsync(BankOnlineShopConsumer.BankReference.HistoryTransaction historyTransaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/GetTransactionList", ReplyAction="http://tempuri.org/IBank/GetTransactionListResponse")]
        BankOnlineShopConsumer.BankReference.Transaction[] GetTransactionList(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/GetTransactionList", ReplyAction="http://tempuri.org/IBank/GetTransactionListResponse")]
        System.Threading.Tasks.Task<BankOnlineShopConsumer.BankReference.Transaction[]> GetTransactionListAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/GetPartnerById", ReplyAction="http://tempuri.org/IBank/GetPartnerByIdResponse")]
        BankOnlineShopConsumer.BankReference.PartnerAccount GetPartnerById(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/GetPartnerById", ReplyAction="http://tempuri.org/IBank/GetPartnerByIdResponse")]
        System.Threading.Tasks.Task<BankOnlineShopConsumer.BankReference.PartnerAccount> GetPartnerByIdAsync(long id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankChannel : BankOnlineShopConsumer.BankReference.IBank, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankClient : System.ServiceModel.ClientBase<BankOnlineShopConsumer.BankReference.IBank>, BankOnlineShopConsumer.BankReference.IBank {
        
        public BankClient() {
        }
        
        public BankClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddCustomer(BankOnlineShopConsumer.BankReference.Customer customer) {
            return base.Channel.AddCustomer(customer);
        }
        
        public System.Threading.Tasks.Task<bool> AddCustomerAsync(BankOnlineShopConsumer.BankReference.Customer customer) {
            return base.Channel.AddCustomerAsync(customer);
        }
        
        public bool AddAccount(BankOnlineShopConsumer.BankReference.Account account) {
            return base.Channel.AddAccount(account);
        }
        
        public System.Threading.Tasks.Task<bool> AddAccountAsync(BankOnlineShopConsumer.BankReference.Account account) {
            return base.Channel.AddAccountAsync(account);
        }
        
        public bool LoginAccount(BankOnlineShopConsumer.BankReference.Account customer) {
            return base.Channel.LoginAccount(customer);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAccountAsync(BankOnlineShopConsumer.BankReference.Account customer) {
            return base.Channel.LoginAccountAsync(customer);
        }
        
        public bool AddPartnerAccount(BankOnlineShopConsumer.BankReference.PartnerAccount account) {
            return base.Channel.AddPartnerAccount(account);
        }
        
        public System.Threading.Tasks.Task<bool> AddPartnerAccountAsync(BankOnlineShopConsumer.BankReference.PartnerAccount account) {
            return base.Channel.AddPartnerAccountAsync(account);
        }
        
        public bool LoginPartnerAccount(BankOnlineShopConsumer.BankReference.PartnerAccount partner) {
            return base.Channel.LoginPartnerAccount(partner);
        }
        
        public System.Threading.Tasks.Task<bool> LoginPartnerAccountAsync(BankOnlineShopConsumer.BankReference.PartnerAccount partner) {
            return base.Channel.LoginPartnerAccountAsync(partner);
        }
        
        public int AddTransaction(BankOnlineShopConsumer.BankReference.Transaction transaction) {
            return base.Channel.AddTransaction(transaction);
        }
        
        public System.Threading.Tasks.Task<int> AddTransactionAsync(BankOnlineShopConsumer.BankReference.Transaction transaction) {
            return base.Channel.AddTransactionAsync(transaction);
        }
        
        public bool AddHistoryTransaction(BankOnlineShopConsumer.BankReference.HistoryTransaction historyTransaction) {
            return base.Channel.AddHistoryTransaction(historyTransaction);
        }
        
        public System.Threading.Tasks.Task<bool> AddHistoryTransactionAsync(BankOnlineShopConsumer.BankReference.HistoryTransaction historyTransaction) {
            return base.Channel.AddHistoryTransactionAsync(historyTransaction);
        }
        
        public BankOnlineShopConsumer.BankReference.Transaction[] GetTransactionList(string id) {
            return base.Channel.GetTransactionList(id);
        }
        
        public System.Threading.Tasks.Task<BankOnlineShopConsumer.BankReference.Transaction[]> GetTransactionListAsync(string id) {
            return base.Channel.GetTransactionListAsync(id);
        }
        
        public BankOnlineShopConsumer.BankReference.PartnerAccount GetPartnerById(long id) {
            return base.Channel.GetPartnerById(id);
        }
        
        public System.Threading.Tasks.Task<BankOnlineShopConsumer.BankReference.PartnerAccount> GetPartnerByIdAsync(long id) {
            return base.Channel.GetPartnerByIdAsync(id);
        }
    }
}
